template_path: infrastructure/t_ecs-cluster.yaml
dependencies:
  - dev/vpc.yaml
  - dev/security-groups.yaml
  - dev/load-balancers.yaml
  - dev/postgresdb.yaml
  - dev/ec2-instance-dbinit.yaml

parameters: 
   VPC: !stack_output vpc.yaml::VPC
   EnvironmentName: {{ var.EnvironmentName }}
   #EnvironmentName: !stack_output vpc.yaml::EnvironmentName
   InstanceType: t2.micro
   EnvType: {{ var.EnvType }}
   #
   EC2keypair: {{ var.EC2keypair }}
   #
   #DEV
   SecurityGroup: !stack_output security-groups.yaml::TestingSecurityGroup
   Subnets: !stack_output vpc.yaml::PublicSubnets
   #PROD
   #SecurityGroup: !stack_output security-groups.yaml::ECSHostSecurityGroup
   #Subnets: !stack_output vpc.yaml::PrivateSubnets 
   #
   DBPort: !stack_output postgresdb.yaml::DBPort
   DBHost: !stack_output postgresdb.yaml::VTTDBHOST
   ListenHost: !stack_output postgresdb.yaml::VTTLISTENHOST
   ListenPort: !stack_output postgresdb.yaml::VTTLISTENPORT    
   DBName: {{ var.DBName }}
   DBMasterUsername: {{ var.DBMasterUsername }}
   DBMasterUserPassword: {{ var.DBMasterUserPassword }}
   InitialClusterSize: "2"
   MinClusterSize: "2"
   MaxClusterSize: "4"
