template_path: db/t_postgresdb.yaml
dependencies:
  - dev/vpc.yaml
  - dev/security-groups.yaml
  - dev/load-balancers.yaml
parameters: 
   EnvironmentName: !stack_output vpc.yaml::EnvironmentName
   #
   #For DEV setup put the DB in the Public subnet and the special public security group
   DatabaseSecurityGroup: !stack_output security-groups.yaml::TestingSecurityGroup
   MyDBSubnets: !stack_output vpc.yaml::PublicSubnets
   #
   #For Prod
   #DatabaseSecurityGroup: stack_output security-groups.yaml::DatabaseSecurityGroup
   #MyDBSubnets: !stack_output vpc.yaml::DBPrivateSubnets   
   #
   DBInstanceClass: db.t2.micro
   #
   #Note that some of the below should move into variables for security later
   DBName: "techtest"
   DBMasterUsername: "postgres"
   DBMasterUserPassword: "jpassword"
   DBPort: "5432"
 