template_path: db/t_postgresdb.yaml
dependencies:
  - dev/vpc.yaml
  - dev/security-groups.yaml
  - dev/load-balancers.yaml
parameters: 
   EnvironmentName: {{ var.EnvironmentName }}
   #
   #For DEV setup put the DB in the Public subnet and the special public security group
   DatabaseSecurityGroup: !stack_output security-groups.yaml::TestingSecurityGroup
   MyDBSubnets: !stack_output vpc.yaml::PublicSubnets
   #
   #For Prod
   #DatabaseSecurityGroup: stack_output security-groups.yaml::DatabaseSecurityGroup
   #MyDBSubnets: !stack_output vpc.yaml::DBPrivateSubnets   
   #
   DBInstanceClass: db.t2.micro
   #
   #
   DBPort: "5432"
   DBName: {{ var.DBName }}
   DBMasterUsername: {{ var.DBMasterUsername }}
   DBMasterUserPassword: {{ var.DBMasterUserPassword }}
   EngineVersion: "9.6.11" 

   

 